### ISSUE TITLE
Bug: Plugin Bundle do not work with Joplin 2.10.2

### ISSUE THREAD

**Issue by makaanneo** [SeptemberHX/joplin-plugin-bundle#30]
Hmm, may an issue with 2.10

# version
## Joplin
Joplin 2.10.2 (dev, win32)
Sync-Version: 3
Profil-Version: 41
Revision: 0a65d53
## plugin
Plugin 0.5.4

# Steps to reproduce
Start Joplin

I tried the plugin in dev mode and got an exception

`Uncaught Error: Cannot find module '../../node_modules/@joplin/lib/node_modules/sqlite3/sqlite3.js'
Require stack:
- C:\Program Files\Joplin\resources\app.asar\services\plugins\plugin_index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at target (plugin_index.js:56:12)
    at newTarget (C:\Program Files\Joplin\resources\app.asar\vendor\lib\@joplin\lib\services\plugins\sandboxProxy.js:21:11)
    at handler.apply (C:\Program Files\Joplin\resources\app.asar\vendor\lib\@joplin\lib\services\plugins\sandboxProxy.js:35:9)`

**Comment by SeptemberHX** [comment]
It should be fixed: https://github.com/laurent22/joplin/releases/tag/v2.10.4
